### ISSUE TITLE
file-attribute-normal is not defined

### ISSUE THREAD

**Issue by gingeralesy** [Shinmera/mmap#1]
in `windows.lisp` there is a function `translate-open-flags`. It defines variable `flag` to the value of `file-attribute-normal`, but unlike all the other constants, this one is not defined. This is the only file with a reference to `file-attribute-normal`.

**Comment by Shinmera** [comment]
The dirty secret is that I never actually tested this to work properly on Windows, only implemented it according to docs. Welp!
