### ISSUE TITLE
full call to SB-C::UNSIGNED+SIGNED

### ISSUE THREAD

**Issue by PF00517** [Shinmera/mmap#13]
In file windows.lisp I get an error when I run the %mmap function on line 118. Here is what it says in the debugger: 

full call to SB-C::UNSIGNED+SIGNED
This is probably a bug in SBCL itself. (Alternatively, SBCL
might have been corrupted by bad user code, e.g. by an undefined
Lisp operation like (FMAKUNBOUND 'COMPILE), or by stray pointers
from alien code or from unsafe Lisp code; or there might be a
bug in the OS or hardware that SBCL is running on.) If it seems
to be a bug in SBCL itself, the maintainers would like to know
about it. Bug reports are welcome on the SBCL mailing lists,
which you can find at <http://sbcl.sourceforge.net/>. 

I've certainly posted about the bug where I've been asked and am waiting for a response, but perhaps you know what I might have had wrong.

**Comment by Shinmera** [comment]
Update SBCL.

**Comment by PF00517** [comment]
I have SBCL 2.3.2 on windows. I even reinstalled to be sure it wasn't the problem. 

If that somehow defines my problem, here are my *features*:

(CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:WINDOWS :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :WINDOWS :QUICKLISP
 :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-WINDOWS
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :ARENA-ALLOCATOR :X86-64 :GENCGC :64-BIT
 :ANSI-CL :COMMON-LISP :IEEE-FLOATING-POINT :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-LDB :SB-PACKAGE-LOCKS :SB-SAFEPOINT :SB-THREAD
 :SB-UNICODE :SBCL :WIN32)

I just have no idea where to look for the error

**Comment by Shinmera** [comment]
2.3.2 has a bug that triggers this. It was fixed in later releases. SBCL is currently at 2.3.7.

**Comment by PF00517** [comment]
On windows there is only 2.3.2 on the sbcl.org website

**Comment by Shinmera** [comment]
You'll have to compile it from source, then. It's not a bug in mmap, so there's nothing else I can do.

**Comment by PF00517** [comment]
Ok, thanks
