### ISSUE TITLE
Features 64-bit and 32-bit are not portable

### ISSUE THREAD

**Issue by Yehouda** [Shinmera/mmap#6]
In file posix.lisp it is using the features **32-bit** and **64-bit** when defining **size-t** and **offset-t**. These features are not portatble.

CFFI has some features like **cffi-features:x86-64** and **cffi-features:sparc64**, but they don't have a generic 64/32 distinction. 

At the moment I think the most portable approach is to check what `(> (logcount most-positive-fixnum) 32)` returns.

**Comment by Shinmera** [comment]
These features should be provided by trivial-features, which mmap does depend on.

**Comment by Yehouda** [comment]
Where do you get trivial-features from?

Neither 32-bit nor 64-bit appears in https://github.com/trivial-features/trivial-features

**Comment by Shinmera** [comment]
Hmm, I might have misremembered then. Do you have a particular implementation where this is a problem, or?

**Comment by Yehouda** [comment]
LispWorks.

**Comment by luismbo** [comment]
Using `(cffi:foreign-type-size :pointer)` or aliasing those `size-t` and `offset-t` to `:uintptr` might be safe bets. CFFI should probably define these standard C types. 🤔

**Comment by Shinmera** [comment]
Having a size-t and offset-t in cffi is something I've wanted for a while.

**Comment by Shinmera** [comment]
Fixed with trivial-features/trivial-features#14 at least until we get a size-t and offset-t in cffi.
