### ISSUE TITLE
Invalid file handle opening to write on Windows10

### ISSUE THREAD

**Issue by ICanCAD** [Shinmera/mmap#7]
This is Windows 10, 64bit SBCL 2.0.0. Mmap works great for reading file - very helpful. Thank you.
But it seems to fail when attempting to write.
Example failing code is:
C:\Users\MartinM>sbcl
This is SBCL 2.0.0, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.
* (ql::quickload :mmap)
To load "mmap":
  Load 1 ASDF system:
    mmap
; Loading "mmap"
.
(:MMAP)
* (mmap::with-mmap
   (add fd size "c:/temp/temp.tst"
     :open       '(:write :create)
     :protection '(:write)
     :mmap       '(:private)
     :size 1000)
   add)

debugger invoked on a MMAP:MMAP-ERROR in thread
#<THREAD "main thread" RUNNING {10010B0523}>:
  Failed to mmap file (E6):
  The handle is invalid.

(Note: I cloned your repository yesterday and added it to my system so quickload is finding that local system)

**Comment by Shinmera** [comment]
There's two parts to this issue -- one was a bug I pushed a fix for yesterday, the other is a peculiarity of the Windows mmap facility, namely that you cannot mmap something without also requesting :read, and thus also having :read on the file handle.

I've pushed a fix that gives a more comprehensible error message to help with this problem.
